---
title: "RNAseqAnalysis"
author: "Mhyles Hintural"
date: "26/08/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set-up

```{r}
library(plyr)
library(reshape2)
library(dplyr)
library(tidyverse)
library(magrittr)
library(edgeR)
library(RColorBrewer)
library(limma)
library(ggplot2)
library(readxl)
library(pheatmap)
library(here)
library(xtable)
library(biomaRt)
library(org.Hs.eg.db)
library(factoextra)
```

# Data packaging
## Importing count data

```{r ImportCounts}
 
# Read in bam counts
termPlacentaCounts <- read.table(here("RNAseq/rawData/bam_counts.table.tsv"),
                                 sep = '\t',
                                 header = TRUE,
                                 row.names = "Geneid") %>% 
  dplyr::select(., starts_with(c("SCP", "STP")))

 
# clean up the column headers and remove the file extension names
names(termPlacentaCounts) <- gsub("_Aligned.sortedByCoord.out.bam", "", names(termPlacentaCounts))
 
 
names <- names(termPlacentaCounts) %>%
  as.data.frame() %>%
  separate(., col = ., into = c("cohort", "samplenumber", "tissue", "lane"), sep = "_") %>%
  mutate(., samplename = paste(cohort, samplenumber, sep = "")) %>%
  dplyr::select(., samplename)
 
# convert back to a vector so I can overwrite the colnames in the counts table
names <- names[,]
 
# replace the old sample names with the new names
names(termPlacentaCounts) <- names
```

## Importing meta-data

```{r ImportMetadata}

# Read in metadata

simpleMetadata <- read_excel(here("RNAseq/cleanData/simpleMetadata_matched.xlsx"))

```

## Creating a DGEList

```{r DGEList}

# new data frame of gene names for DGEList object
genes <- as.character(rownames(termPlacentaCounts)) %>%
  as.data.frame() %>%
  set_colnames("SYMBOL")

# new DGEList object for differential expression analysis
DGEList_placenta <- DGEList(counts = termPlacentaCounts,
                            samples = simpleMetadata,
                            genes = genes)

```

# Data pre-processing
## Visualise distribution of expression prior to filtering

```{r pre-filtering}

cpm <- cpm(DGEList_placenta)
lcpm <-cpm(DGEList_placenta, log=TRUE)

nsamples <- ncol(DGEList_placenta)
col = colorRampPalette(brewer.pal(11,"Spectral"))(ncol(DGEList_placenta))
par(mfrow=c(1,2))
plot(density(lcpm[,1]), col=col[1], lwd=2, ylim=c(0,1.5), las=2,
     main="", xlab="")
title(main="A. Raw data", xlab="Log-cpm")
abline(v=0, lty=3)
for (i in 2:nsamples){
  den <- density(lcpm[,i])
  lines(den$x, den$y, col=col[i], lwd=2)
}

```

## Removing low expression genes

``` {r filterLow}

# which genes are expressed at > 1 counts per million, in at least 6 samples
# we choose 6 samples because prelabour LSCS has 6 patients, which is our smallest group
keep.exprs <- rowSums(cpm >1) >= 6
keep.exprs %>% table()
# only keep the genes that met the criteria above
DGEList_placenta <- DGEList_placenta[keep.exprs,, keep.lib.sizes = FALSE]

```

## Visualise distribution of expression after filtering

```{r post-filtering}

cpm_post <- cpm(DGEList_placenta)
lcpm_post <-cpm(DGEList_placenta, log=TRUE)
nsamples <- ncol(DGEList_placenta)
col = colorRampPalette(brewer.pal(11,"Spectral"))(ncol(DGEList_placenta))
par(mfrow=c(1,2))
plot(density(lcpm_post[,1]), col=col[1], lwd=2, ylim=c(0,0.70), las=2,
     main="", xlab="")
title(main="A. Raw data", xlab="Log-cpm")
abline(v=0, lty=3)
for (i in 2:nsamples){
  den <- density(lcpm_post[,i])
  lines(den$x, den$y, col=col[i], lwd=2)
}

# Plot the distribution of un-normalised counts
un_normalised_lcpm_post <- cpm(DGEList_placenta, log=TRUE)
boxplot(un_normalised_lcpm_post, las=2, col=col, main="")
title(main = "Placenta: Un-normalised data (RNA)", ylab = "Log-cpm") 

```

## Normalising gene expression distributions

``` {r Normalisation}

DGEList_placenta <- calcNormFactors(x, method = "TMM")
DGEList_placenta$samples$norm.factors
x2 <- DGEList_placenta
x2$samples$norm.factors <- 1
x2$counts[,1] <- ceiling(x2$counts[,1]*0.05)
x2$counts[,2] <- x2$counts[,2]*5
par(mfrow=c(1,2))
lcpm <- cpm(x2, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="A. Unnormalised data",ylab="Log-cpm")
x2 <- calcNormFactors(x2)  
x2$samples$norm.factors
lcpm <- cpm(x2, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="B. Normalised data",ylab="Log-cpm")

```

## Unsupervised clustering of samples

``` {r MDSplots}

lcpm <- cpm(DGEList_placenta, log=TRUE)
par(mfrow=c(1,2))
# col.group <- nsamples
# levels(col.group) <-  brewer.pal(nlevels(col.group), "Set1")
# col.group <- as.character(col.group)
# col.lane <- lane
# levels(col.lane) <-  brewer.pal(nlevels(col.lane), "Set2")
# col.lane <- as.character(col.lane)
# plotMDS(lcpm, labels=delivery_mode, col=col.group)
# title(main="A. Sample groups")
# plotMDS(lcpm, labels=lane, col=col.lane, dim=c(3,4))
# title(main="B. Sequencing lanes")

col.mode <- DGEList_placenta$samples$delivery_mode
levels(col.mode) <-  brewer.pal(nlevels(col.mode), "Set1")
col.mode <- as.character(col.mode)

plotMDS(lcpm)

# MDS filtered and normalised counts

MDS <- plotMDS(DGEList_placenta, main = "MDS Filtered and Normalised Counts")

# pull out the x and y
x <- MDS$x
y <- MDS$y

# plot with ggplot to observe delivery mode vs fetal sex

cbind(x,y) %>%
  as.data.frame() %>% 
  tibble::rownames_to_column("samplename") %>% 
  full_join(., DGEList_placenta$samples, by = "samplename") %>% 
  ggplot() +
  geom_point(aes(x = x,
                 y = y,
                 colour = delivery_mode,
                 shape = fetal_sex),
             size = 6) +
  geom_text(aes(x = x,
                y = y,
                label = samplename,
                colour = delivery_mode), vjust = -1) +
  labs(title = "MDS plot filtered and normalised counts",
       x = "Dim 1",
       y = "Dim 2") +
  theme_bw()

# plot with ggplot to observe delivery mode vs patient outcome

cbind(x,y) %>%
  as.data.frame() %>% 
  tibble::rownames_to_column("samplename") %>% 
  full_join(., DGEList_placenta$samples, by = "samplename") %>% 
  ggplot() +
  geom_point(aes(x = x,
                 y = y,
                 colour = delivery_mode,
                 shape = PatientOutcome),
             size = 6) +
  geom_text(aes(x = x,
                y = y,
                label = samplename,
                colour = delivery_mode), vjust = -1) +
  labs(title = "MDS plot filtered and normalised counts",
       x = "Dim 1",
       y = "Dim 2") +
  theme_bw()

# plot with ggplot to observe delivery mode vs maternal BMI

cbind(x,y) %>%
  as.data.frame() %>% 
  tibble::rownames_to_column("samplename") %>% 
  full_join(., DGEList_placenta$samples, by = "samplename") %>% 
  ggplot() +
  geom_point(aes(x = x,
                 y = y,
                 colour = BMI,
                 shape = delivery_mode),
             size = 6) +
  geom_text(aes(x = x,
                y = y,
                label = samplename,
                colour = BMI), vjust = -1) +
  labs(title = "MDS plot filtered and normalised counts",
       x = "Dim 1",
       y = "Dim 2") +
  theme_bw()

# plot with ggplot to observe delivery mode vs birth weight

cbind(x,y) %>%
  as.data.frame() %>% 
  tibble::rownames_to_column("samplename") %>% 
  full_join(., DGEList_placenta$samples, by = "samplename") %>% 
  ggplot() +
  geom_point(aes(x = x,
                 y = y,
                 colour = birthwgt,
                 shape = delivery_mode),
             size = 6) +
  geom_text(aes(x = x,
                y = y,
                label = samplename,
                colour = birthwgt), vjust = -1) +
  labs(title = "MDS plot filtered and normalised counts",
       x = "Dim 1",
       y = "Dim 2") +
  theme_bw()

# plot with ggplot to observe delivery mode vs maternal age

cbind(x,y) %>%
  as.data.frame() %>% 
  tibble::rownames_to_column("samplename") %>% 
  full_join(., DGEList_placenta$samples, by = "samplename") %>% 
  ggplot() +
  geom_point(aes(x = x,
                 y = y,
                 colour = maternalAge,
                 shape = delivery_mode),
             size = 6) +
  geom_text(aes(x = x,
                y = y,
                label = samplename,
                colour = maternalAge), vjust = -1) +
  labs(title = "MDS plot filtered and normalised counts",
       x = "Dim 1",
       y = "Dim 2") +
  theme_bw()

```